### ISSUE TITLE
any plans to support tokio 1.x?

### ISSUE THREAD

**Issue by yorkart** [vvvy/webhdfs-rs#9]

**Comment by vvvy** [comment]
The code for tokio 1.2 is available under 'feature/tokio-1' branch (it compiles ok but no integration testing yet). I plan to merge it and release to crates.io on the week starting March 8th.

**Comment by yorkart** [comment]
hyper = { version = "0.14", features = ["client", "http1", "stream"] }

**Comment by yorkart** [comment]
Thanks! Can the following components be upgraded together?
hyper = { version = "0.14", features = ["client", "http1", "stream"] }
hyper-tls = "0.5"
bytes = "1.0"

**Comment by vvvy** [comment]
fixed in 0.3.3
